
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class bookings extends javax.swing.JInternalFrame {

    /**
     * Creates new form bookings
     */Connection con;
     ArrayList discountlist = new ArrayList();
     ArrayList couponlist = new ArrayList();
      ArrayList packlist = new ArrayList();
     int chk,flag;
     Validations val;
       Vector data;
     String empid;
    public bookings(Connection con,String empid) {
        initComponents();
        this.con = con;
        this.empid=empid;
        chk=0;
        flag=0;
        filldiscount();
      
        fillpackage();
        val = new Validations();
          data=new Vector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        cmbpack = new javax.swing.JComboBox<>();
        cmbdiscount = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txttax = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        dob = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        btnbook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setText("Customer Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 76, 120, 18);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(45, 116, 0, 0);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(45, 276, 90, 18);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(45, 176, 120, 18);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setText("Package");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(45, 223, 80, 18);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setText("Discount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 140, 80, 18);
        getContentPane().add(txtname);
        txtname.setBounds(228, 73, 140, 27);
        getContentPane().add(txtbookid);
        txtbookid.setBounds(228, 122, 140, 27);
        getContentPane().add(txtcontact);
        txtcontact.setBounds(228, 173, 140, 27);

        getContentPane().add(cmbpack);
        cmbpack.setBounds(228, 220, 140, 27);

        getContentPane().add(cmbdiscount);
        cmbdiscount.setBounds(550, 130, 130, 27);

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setText("Tax");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 250, 60, 18);
        getContentPane().add(txttax);
        txttax.setBounds(550, 240, 130, 27);

        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel10.setText("Booking Id");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(45, 125, 90, 18);
        getContentPane().add(txtemail);
        txtemail.setBounds(228, 273, 140, 27);

        jLabel11.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel11.setText("Booking period");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 290, 110, 18);

        txtconfirm.setText("Advance");
        getContentPane().add(txtconfirm);
        txtconfirm.setBounds(550, 290, 120, 27);

        jLabel12.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel12.setText("Date of Booking");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(45, 338, 120, 18);

        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(228, 334, 146, 27);

        jLabel13.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel13.setText("Total");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(418, 338, 70, 18);
        getContentPane().add(total2);
        total2.setBounds(544, 338, 105, 0);

        btnbook.setBackground(new java.awt.Color(0, 153, 255));
        btnbook.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnbook.setForeground(new java.awt.Color(255, 255, 255));
        btnbook.setText("Book");
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        getContentPane().add(btnbook);
        btnbook.setBounds(360, 530, 154, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 400, 664, 92);

        btnadd.setBackground(new java.awt.Color(0, 153, 255));
        btnadd.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(170, 530, 145, 50);

        jLabel14.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel14.setText("Age");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 200, 60, 18);
        getContentPane().add(txtage);
        txtage.setBounds(550, 190, 130, 27);

        jLabel8.setBackground(new java.awt.Color(255, 204, 51));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("               Ticket Booking");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 10, 450, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tickpng.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(600, 0, 110, 110);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 710, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed
         
         try {
             String contact = txtcontact.getText();
             String email = txtemail.getText();
             String age = txtage.getText();
             String s="";
             if(txtconfirm.isSelected())
             {
                 s= "Advance";
             }
             else
             {
                 s= "";
             }
             
             
             String dd = null;
             int count=0;
             
             TableModel tm = jTable1.getModel();
             for (int i = 0; i < jTable1.getRowCount(); i++) {
                 
                 String bookid = (String) tm.getValueAt(i, 0);
                 String custname = (String) tm.getValueAt(i, 1);
                 String dis = (String) tm.getValueAt(i, 2);
                 
                 String pack = (String) tm.getValueAt(i, 3);
                 String tax = (String) tm.getValueAt(i, 4);
                  dd = (String) tm.getValueAt(i, 5);
                 String price = (String) tm.getValueAt(i, 6);
             
             String sql = "insert into bookings(booking_id, customer_name, email_id, contact_number,discount_id,age,package_id,employee_id,tax,date_of_booking,status,total_price) values(?,?,?,?,?,?,?,?,?,?,?,?)";
             PreparedStatement p = con.prepareStatement(sql);
             
             p.setString(1, bookid);
             p.setString(2, custname);
             p.setString(3, email);
             p.setString(4, contact);
             p.setString(5, dis);
             p.setString(6, age);
             p.setString(7, pack);
             p.setString(8, empid);
             p.setString(9, tax);
             p.setString(10, dd);
             p.setString(11,s);
             p.setString(12,price);
             p.executeUpdate();
             count++;
             }
               String subject="test";
               String message="<b> Welcome to Theme Park\n</b>\nYour booking is confirmed! with the following details\n Booking Date: "+dd+"Number of tickets: "+count+"<b>Thankyou</b>\n<b>Have Fun Visit Again!</b>";
             
              sendmail m=new sendmail();
       m.sendEmail(email,subject,message);
             JOptionPane.showMessageDialog(this, "booking confirmed");
         } catch (Exception ex) {
             Logger.getLogger(bookings.class.getName()).log(Level.SEVERE, null, ex);
         }
           
         
                    


               
    }//GEN-LAST:event_btnbookActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        fillTable();
    }//GEN-LAST:event_btnaddActionPerformed
 void filldiscount()
    {
        try{
        String query="select * from discount" ;
PreparedStatement ps= con.prepareStatement(query);
 

 ResultSet rs=ps.executeQuery();

 
  String discount_array[]=new String[3];
     
    // discountlist.add(discount_array);
 while(rs.next()){
      discount_array=new String[3];
     discount_array[0]=rs.getString("discount_id");
     discount_array[1]=rs.getString("discount_name");
     discount_array[2]=rs.getString("discount_percentage");
     cmbdiscount.addItem(rs.getString("discount_name"));
      discountlist.add(discount_array);
 }
 chk =1;
 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
    
 
   void fillpackage()
    {
        try{
        String query="select * from package1" ;
PreparedStatement ps= con.prepareStatement(query);
 

 ResultSet rs=ps.executeQuery();

 
  String package_array[]=new String[3];
     
    // packlist.add(package_array);
 while(rs.next()){
      package_array=new String[3];
      package_array[0]=rs.getString("pack_id");
      package_array[1]=rs.getString("package_name");
      package_array[2]=rs.getString("total_price");
     cmbpack.addItem(rs.getString("package_name"));
      packlist.add(package_array);
 }
 chk =1;
 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
     void fillTable() {
        try {
            Vector heading = new Vector();
            heading.add("Booking_id");
            heading.add("Customer_Name");
            heading.add("Discount");
            heading.add("Package");
             heading.add("Tax");
              heading.add("Date Of Booking");
              
                heading.add("Price");
String custname = txtname.getText();
            val.isName(custname);
            if(custname.length() == 0)
            {
                JOptionPane.showMessageDialog(this, "Please fill name");
                return;
            }
            String bookid = txtbookid.getText();
          
            
            int pack = cmbpack.getSelectedIndex();
            String x[]=(String[]) packlist.get(pack);
             String packg=x[0];
             String pack1= x[2];
            
            
            int discount = cmbdiscount.getSelectedIndex();
             String y[]=(String[]) discountlist.get(discount);
             String dis = y[0];
             String dis1= y[2];
  
             
       Date dh=dob.getDate();
       SimpleDateFormat sd=new SimpleDateFormat("dd/MM/yyyy");
             String dob = sd.format(dh);
            if(dob.length() == 0)
            {
                JOptionPane.showMessageDialog(this, "Please Fill Date Of Booking");
                return;
            }
             
              String age = txtage.getText();
            
        int a,b,c,d;
        double total;
      a =   Integer.parseInt(dis1);
      b =   Integer.parseInt(pack1);
     
      String tt= txttax.getText();
      d = Integer.parseInt(tt); 
      
      total = (b - 0.01*a*b) + (0.01*d*b);
      String total1= String.valueOf(total);
      int totalfinal = (int)total;
      total2.setText(String.valueOf(totalfinal));
      
      
            

           
 
            Vector row = new Vector();
            row.add(bookid);
            row.add(custname);
            row.add(String.valueOf(discount));
            row.add(packg);
            row.add(tt);
            row.add(dob);

            row.add(String.valueOf(totalfinal));
            
            data.add(row);
            DefaultTableModel df = new DefaultTableModel(data, heading);
            jTable1.setModel(df);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error occured " + ex.getMessage());
            ex.printStackTrace();
        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbook;
    private javax.swing.JComboBox<String> cmbdiscount;
    private javax.swing.JComboBox<String> cmbpack;
    private org.jdesktop.swingx.JXDatePicker dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel total2;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JCheckBox txtconfirm;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttax;
    // End of variables declaration//GEN-END:variables
}
