
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class ChangePasswordmi extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePasswordmi
     */
    Connection con;
    public ChangePasswordmi(Connection con) {
        initComponents();
        this.con = con;
        setTitle("Change Password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtold = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnew = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtconfirm = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 90, 26);

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel1.add(txtuser);
        txtuser.setBounds(220, 50, 130, 25);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Old password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 100, 90, 21);

        txtold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoldActionPerformed(evt);
            }
        });
        jPanel1.add(txtold);
        txtold.setBounds(220, 100, 130, 25);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("New Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 150, 96, 21);

        txtnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewActionPerformed(evt);
            }
        });
        jPanel1.add(txtnew);
        txtnew.setBounds(220, 150, 130, 25);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Confirm Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 200, 120, 21);

        txtconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmActionPerformed(evt);
            }
        });
        jPanel1.add(txtconfirm);
        txtconfirm.setBounds(220, 200, 130, 25);

        btnChange.setBackground(new java.awt.Color(0, 153, 255));
        btnChange.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnChange.setText("Change Password");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnChange);
        btnChange.setBounds(128, 263, 150, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 380, 330);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Light-Pink-Background-Wallpaper.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 380, 346);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
         try
        {
       String username=txtuser.getText();
       String oldpassword=txtold.getText();
       String newpassword=txtnew.getText();
       String confirmpassword= txtconfirm.getText();
        

        
String query="select * from login where username=? and password=?";
PreparedStatement ps=con.prepareStatement(query);
 ps.setString(1, username);
 ps.setString(2, oldpassword);
 int count=ps.executeUpdate();
       if (count==1)
       {
          if(newpassword.equals(confirmpassword)) 
          {
   String query1="update login set password=? where username=?";
PreparedStatement ps1=con.prepareStatement(query1);
 ps1.setString(1, newpassword);
 ps1.setString(2, username);
ps1.executeUpdate();
JOptionPane.showMessageDialog(this, "Password Changed");
        }
          else
          {
             JOptionPane.showMessageDialog(this, "Password does not match");
            
          }
           
           
       }
       else
       {
           JOptionPane.showMessageDialog(this, "No Record Exists");
           
       }
        
        
        
        
        
        
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btnChangeActionPerformed

    private void txtnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewActionPerformed

    private void txtconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmActionPerformed

    private void txtoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoldActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtconfirm;
    private javax.swing.JTextField txtnew;
    private javax.swing.JTextField txtold;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
