
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class ChangePassword2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePassword2
     */Connection con;
    public ChangePassword2(Connection con) {
        initComponents();
        this.con = con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtold = new javax.swing.JTextField();
        txtnew = new javax.swing.JTextField();
        txtconfirm = new javax.swing.JTextField();
        btncp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 120, 90, 23);

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setText("Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 180, 140, 30);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 250, 150, 23);

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 310, 160, 30);
        getContentPane().add(txtuser);
        txtuser.setBounds(340, 250, 148, 25);
        getContentPane().add(txtold);
        txtold.setBounds(340, 120, 148, 25);

        txtnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewActionPerformed(evt);
            }
        });
        getContentPane().add(txtnew);
        txtnew.setBounds(340, 180, 148, 25);
        getContentPane().add(txtconfirm);
        txtconfirm.setBounds(340, 320, 148, 25);

        btncp.setBackground(new java.awt.Color(51, 153, 255));
        btncp.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        btncp.setForeground(new java.awt.Color(255, 255, 255));
        btncp.setText("Change Password");
        btncp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncpActionPerformed(evt);
            }
        });
        getContentPane().add(btncp);
        btncp.setBounds(270, 380, 170, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ccc.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 690, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncpActionPerformed
          try
        {
       String username=txtuser.getText();
       String oldpassword=txtold.getText();
       String newpassword=txtnew.getText();
       String confirmpassword= txtconfirm.getText();
        

        
String query="select * from employee where emp_id=?  and password=?";
PreparedStatement ps=con.prepareStatement(query);
 ps.setString(1, username);
 ps.setString(2, oldpassword);
 int count=ps.executeUpdate();
       if (count==1)
       {
          if(newpassword.equals(confirmpassword)) 
          {
   String query1="update employee set password=? where emp_id=?";
PreparedStatement ps1=con.prepareStatement(query1);
 ps1.setString(1, newpassword);
 ps1.setString(2, username);
ps1.executeUpdate();
JOptionPane.showMessageDialog(this, "Password Changed");
        }
          else
          {
             JOptionPane.showMessageDialog(this, "Password does not match");
            
          }
           
           
       }
       else
       {
           JOptionPane.showMessageDialog(this, "No Record Exists");
           
       }
        
        
        
        
        
        
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btncpActionPerformed

    private void txtnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtconfirm;
    private javax.swing.JTextField txtnew;
    private javax.swing.JTextField txtold;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
