
import static java.lang.Boolean.TRUE;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Employees extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employees
     */
    Connection con;
     ArrayList departmentlist=new ArrayList();
     ArrayList designationlist=new ArrayList();
    int chck,flag;
    Validations val;
    String password;
    
    public Employees(Connection con) {
        initComponents();
        this.con = con;
        
         chck =0;
         flag =0;
        filldept();
       filldesignation();
        val = new Validations();
        fillTable();
       
    }

    private Employees() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    
      void fillTable()
    {
        try
        {
        Vector heading=new Vector();
        heading.add("Emp Code");
        heading.add("Emp Name");
        heading.add("Department");
        heading.add("Designation");
        heading.add("Salary");
        heading.add("Age");
        heading.add("Gender");
        heading.add("Contact no");
        heading.add("Address");
        heading.add("Email ID");
        heading.add("Date Of Join");
        
        
        String query="select * from employee,designation,department where designation.dcode=employee.designation and department.dcode=employee.department";
        PreparedStatement ps=con.prepareStatement(query);
        ResultSet rs=ps.executeQuery();
        Vector data=new Vector();
        while(rs.next())
        {
            Vector row=new Vector();
            row.add(rs.getString("emp_id"));
            row.add(rs.getString("employee_name"));
            row.add(rs.getString("department"));
            row.add(rs.getString("designation"));
            row.add(rs.getString("Salary"));
            row.add(rs.getString("age"));
            row.add(rs.getString("gender"));
            row.add(rs.getString("contact_number"));
            row.add(rs.getString("address"));
             row.add(rs.getString("email_id"));
             row.add(rs.getString("date_of_join"));
               
            data.add(row);
         }
            DefaultTableModel df=new DefaultTableModel(data,heading);
            EmpTable.setModel(df);
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured "+ex.getMessage());
            ex.printStackTrace();
        }
        
    }

    void filldept()
    {
        try{
        String query="select * from department" ;
PreparedStatement ps= con.prepareStatement(query);
 

 ResultSet rs=ps.executeQuery();

 
  String department_array[]=new String[2];
     department_array[0]="select";
     department_array[1]="0";
     cmbdep.addItem("Select");
     departmentlist.add(department_array);
 while(rs.next()){
      department_array=new String[2];
     department_array[0]=rs.getString("dname");
     department_array[1]=rs.getString("dcode");
     cmbdep.addItem(rs.getString("dname"));
     departmentlist.add(department_array);
 }
 chck =1;
 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
    
    void filldesignation()
    {
          try{
        String query="select * from designation" ;
PreparedStatement ps= con.prepareStatement(query);
 

 ResultSet rs=ps.executeQuery();
 
  String desig_array[]=new String[2];
     desig_array[0]="select";
     desig_array[1]="0";
     designationlist.add(desig_array);
   while(rs.next()){
     desig_array= new String[2];
     desig_array[0]=rs.getString("designation");
     desig_array[1]=rs.getString("dcode");
     txtdesig.addItem(rs.getString("designation"));
     designationlist.add(desig_array);
     }
     flag =1;
 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
        
        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtempId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbdep = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdesig = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        rbuttunmale = new javax.swing.JRadioButton();
        rbuttonfemale = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnmodify = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtadress = new javax.swing.JTextArea();
        Ryes = new javax.swing.JRadioButton();
        Rno = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtjoin = new org.jdesktop.swingx.JXDatePicker();
        jLabel15 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 246, 246));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Employee Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(22, 28, 91, 18);

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(166, 26, 147, 25);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Employee Code");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(22, 71, 106, 18);
        jPanel1.add(txtempId);
        txtempId.setBounds(166, 69, 147, 25);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("Department");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(22, 112, 106, 18);

        cmbdep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdepItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbdep);
        cmbdep.setBounds(166, 112, 147, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("Salary");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(22, 158, 38, 18);

        txtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtsalary);
        txtsalary.setBounds(166, 158, 147, 25);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setText("Designation");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(22, 206, 65, 18);

        txtdesig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtdesigItemStateChanged(evt);
            }
        });
        txtdesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesigActionPerformed(evt);
            }
        });
        jPanel1.add(txtdesig);
        txtdesig.setBounds(166, 206, 147, 20);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(22, 246, 22, 18);

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        jPanel1.add(txtage);
        txtage.setBounds(166, 244, 147, 25);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(22, 288, 90, 18);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setText("Contact number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(22, 328, 90, 25);
        jPanel1.add(txtcontact);
        txtcontact.setBounds(166, 329, 147, 25);

        buttonGroup1.add(rbuttunmale);
        rbuttunmale.setText("Male");
        rbuttunmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttunmaleActionPerformed(evt);
            }
        });
        jPanel1.add(rbuttunmale);
        rbuttunmale.setBounds(170, 290, 60, 23);

        buttonGroup1.add(rbuttonfemale);
        rbuttonfemale.setText("female");
        jPanel1.add(rbuttonfemale);
        rbuttonfemale.setBounds(230, 290, 80, 23);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(-40, -10, 100, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 10, 340, 390);

        jPanel2.setBackground(new java.awt.Color(228, 236, 248));
        jPanel2.setLayout(null);

        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        EmpTable.setAlignmentX(1.0F);
        EmpTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EmpTable);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 66, 860, 126);

        btnShow.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel2.add(btnShow);
        btnShow.setBounds(660, 10, 85, 29);

        btnSave.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);
        btnSave.setBounds(90, 10, 59, 29);

        btnmodify.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnmodify.setText("Modify");
        btnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifyActionPerformed(evt);
            }
        });
        jPanel2.add(btnmodify);
        btnmodify.setBounds(240, 10, 69, 29);

        btnNew.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew);
        btnNew.setBounds(390, 10, 57, 29);

        btndel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        jPanel2.add(btndel);
        btndel.setBounds(520, 10, 69, 29);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 430, 860, 190);

        jPanel3.setBackground(new java.awt.Color(252, 246, 246));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel9.setText("Email ID");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 30, 51, 18);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel10.setText("Address");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 80, 48, 18);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel12.setText("Date of Join");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 200, 74, 18);
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 293, 0, 0);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel3.add(txtemail);
        txtemail.setBounds(120, 30, 209, 25);

        txtadress.setColumns(20);
        txtadress.setRows(5);
        jScrollPane3.setViewportView(txtadress);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(120, 80, 209, 73);

        buttonGroup5.add(Ryes);
        Ryes.setText("YES");
        jPanel3.add(Ryes);
        Ryes.setBounds(150, 270, 43, 23);

        buttonGroup5.add(Rno);
        Rno.setText("NO");
        jPanel3.add(Rno);
        Rno.setBounds(150, 300, 41, 23);

        jLabel11.setText("Valid Login");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 290, 80, 14);
        jPanel3.add(txtjoin);
        txtjoin.setBounds(130, 200, 200, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(480, 10, 340, 390);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/d9X4ge.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 890, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String employee_name = txtname.getText().toString();
            val.isName(employee_name);
            if(employee_name.length() == 0)
            {
                JOptionPane.showMessageDialog(this, "Please fill name");
                return;
            }
            String emp_id = txtempId.getText().toString();
            if(emp_id.length() == 0)
            {
                JOptionPane.showMessageDialog(this, "Please fill Employee code");
                return;
            }
            int department = cmbdep.getSelectedIndex();
            String x[]=(String[]) departmentlist.get(department);
             String dcode=x[1];
            
            String salary = txtsalary.getText();
            if(salary.length() == 0)
            {
                JOptionPane.showMessageDialog(this, "Please fill salary");
                return;
            }
            
            int designation = txtdesig.getSelectedIndex();
             String y[]=(String[]) designationlist.get(designation);
             String dcodex = y[1];
             
             String contact = txtcontact.getText();
             if(val.isNumber(contact)== false)
             {
                 JOptionPane.showMessageDialog(this,"Invalid Number");
                 return;
             }
      
             
             
             
             String age = txtage.getText();
             if(age.length()== 0)
             {
                 JOptionPane.showMessageDialog(this,"Enter age");
                 return;
             }
             
             
          String adress = txtadress.getText();
          if(adress.length()==0)
          {
             JOptionPane.showMessageDialog(this, "Enter Address");
             return;
           
           }
          String email = txtemail.getText();
          if(val.validEmail(email))
          {
              JOptionPane.showMessageDialog(this, "Incorrect Email");
              return;
          }
             if(email.length() == 0)
             {
                 JOptionPane.showMessageDialog(this, "Enter email");
                 return;
             }
             String s="";
       if(rbuttunmale.isSelected()) 
       s="male";
       else
           s="female";
             
       Date dh=txtjoin.getDate();
       SimpleDateFormat sd=new SimpleDateFormat("dd/MM/yyyy");
             String doj = sd.format(dh);
            if(doj.length() == 0)
            {
                JOptionPane.showMessageDialog(this, "Please Fill Date Of Join");
                return;
            }
             
             String valid="";
             
       if(Ryes.isSelected()) 
       valid = "Yes";
       else
           valid = "No";
       if(valid == "Yes")
       {
           password = employee_name;
       }
       if(valid== "No")
       {
           password = "";
       }
            
            String sql = "insert into employee(employee_name, emp_id, department, designation, salary,age,gender,address,email_id,contact_number,date_of_join,valid_login,password) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement p = con.prepareStatement(sql);

            p.setString(1, employee_name);
            p.setString(2, emp_id);
            p.setString(3, dcode);
            p.setString(4, dcodex);
            p.setString(5, salary);
            p.setString(6, age);
            p.setString(7, s);
            p.setString(8, adress);
            p.setString(9, email);
            p.setString(10, contact);
            p.setString(11, doj);
            p.setString(12,valid);
            p.setString(13,password);
            p.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data Saved");  
            fillTable();
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbdepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbdepItemStateChanged
        if(chck==1)
        {
        int index=cmbdep.getSelectedIndex();
         String x[]=(String []) departmentlist.get(index);
        }
    }//GEN-LAST:event_cmbdepItemStateChanged

    private void txtdesigItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtdesigItemStateChanged
       if(flag==1)
        {
        int index=txtdesig.getSelectedIndex();
         String x[]=(String []) designationlist.get(index);
        }
    }//GEN-LAST:event_txtdesigItemStateChanged

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
             
            
    }//GEN-LAST:event_btnShowActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed

    }//GEN-LAST:event_txtnameActionPerformed

    private void txtdesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesigActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaryActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
txtname.setText(" ");
txtage.setText(" ");
txtadress.setText(" ");
txtemail.setText("");
txtsalary.setText("");
txtcontact.setText("");
txtempId.setText("");
//txtjoin.setText("");



    }//GEN-LAST:event_btnNewActionPerformed

    private void EmpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpTableMouseClicked
         int rowindex = EmpTable.getSelectedRow();
        TableModel tm = EmpTable.getModel();

        String id = (String) tm.getValueAt(rowindex, 0);
      
        String name = (String) tm.getValueAt(rowindex, 1);
        String depname  = (String) tm.getValueAt(rowindex, 2);
        String design = (String) tm.getValueAt(rowindex, 3);
        String salary = (String) tm.getValueAt(rowindex, 4);
        String age = (String) tm.getValueAt(rowindex, 5);
        String gender = (String) tm.getValueAt(rowindex, 6);
        String contact = (String) tm.getValueAt(rowindex, 7);
        String address = (String) tm.getValueAt(rowindex, 8);
        String mail = (String) tm.getValueAt(rowindex, 9);
        String doj = (String) tm.getValueAt(rowindex, 10);
          txtname.setText(name);
          txtempId.setText(id);
          txtsalary.setText(salary);
          txtadress.setText(address);
          txtage.setText(age);
          txtcontact.setText(contact);
          txtemail.setText(mail);
          
          rbuttunmale.setSelected(TRUE);
          
          
         for(int i=0;i<departmentlist.size();i++)
         {
           String x[]=(String []) departmentlist.get(i);
             if(x[1].equals(depname))
             {
                  cmbdep.setSelectedIndex(i);
                break;
             }
         }
                               System.out.println(designationlist.size());

         
         for(int i=0;i<designationlist.size();i++)
         {
           String x[]=(String []) designationlist.get(i);
             if(x[1].equals(design))
             {
                  txtdesig.setSelectedIndex(i);
                 break;
             }
         }
         
         
         
       



    }//GEN-LAST:event_EmpTableMouseClicked

    private void btnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifyActionPerformed
          try
        {
           
       
        String name2=txtname.getText();
        String dcode = txtempId.getText();

        String salary = txtsalary.getText();
        String age = txtage.getText();
        String contact = txtcontact.getText();
        String address = txtadress.getText();
        String email = txtemail.getText();
       
        int department = cmbdep.getSelectedIndex();
            String x[]=(String[]) departmentlist.get(department);
             String dep=x[1];
            
            
            
            int designation = txtdesig.getSelectedIndex();
             String y[]=(String[]) designationlist.get(designation);
             String des = y[1];
        
        
        String s="";
       if(rbuttunmale.isSelected()) 
       s="male";
       else
           s="female";
               
        
           
        String sql = "update employee set  employee_name =?, department=?, designation=?, salary=? ,age=?, contact_number=?, email_id=?, address=?, gender=? where emp_id =?";

        PreparedStatement p = con.prepareStatement(sql);

        p.setString(1, name2);
        p.setString(2, dep);
        p.setString(3, des);
        p.setString(4, salary);
        p.setString(5, age);
        p.setString(6, contact);
        p.setString(7, email);
        p.setString(8, address);
        p.setString(9, s);
        p.setString(10,dcode);
        p.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data Updated");  
        fillTable();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured "+ex.getMessage());
            ex.printStackTrace();
        }  
        
                                          

    }//GEN-LAST:event_btnmodifyActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        try
        {
            String ecode=txtempId.getText();
       
        String sql = "delete from  employee where emp_id=?";

        PreparedStatement p = con.prepareStatement(sql);
 p.setString(1, ecode);
        p.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data Deleted");  
        fillTable();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured "+ex.getMessage());
            ex.printStackTrace();
        }  
              
    }//GEN-LAST:event_btndelActionPerformed

    private void rbuttunmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttunmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbuttunmaleActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpTable;
    private javax.swing.JRadioButton Rno;
    private javax.swing.JRadioButton Ryes;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnmodify;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cmbdep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbuttonfemale;
    private javax.swing.JRadioButton rbuttunmale;
    private javax.swing.JTextArea txtadress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JComboBox<String> txtdesig;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtempId;
    private org.jdesktop.swingx.JXDatePicker txtjoin;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
