
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class MenuItems extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form MenuItems
     */
    public MenuItems(Connection con) {
        initComponents();
        this.con=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        dp = new DesktopPaneBG();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menucp = new javax.swing.JMenuItem();
        logoutmi = new javax.swing.JMenuItem();
        exitmi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        departmentmi = new javax.swing.JMenuItem();
        designationmi = new javax.swing.JMenuItem();
        Employee = new javax.swing.JMenuItem();
        categorymi = new javax.swing.JMenuItem();
        subcatmi = new javax.swing.JMenuItem();
        mDiscount = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        coupons = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenuItem5.setText("jMenuItem5");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Admin");

        menucp.setText("change password");
        menucp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucpActionPerformed(evt);
            }
        });
        jMenu1.add(menucp);

        logoutmi.setText("Logout");
        logoutmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmiActionPerformed(evt);
            }
        });
        jMenu1.add(logoutmi);

        exitmi.setText("Exit");
        exitmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmiActionPerformed(evt);
            }
        });
        jMenu1.add(exitmi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manage");

        departmentmi.setText("  department");
        departmentmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentmiActionPerformed(evt);
            }
        });
        jMenu2.add(departmentmi);

        designationmi.setText("Designation");
        designationmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationmiActionPerformed(evt);
            }
        });
        jMenu2.add(designationmi);

        Employee.setText(" Employee");
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });
        jMenu2.add(Employee);

        categorymi.setText("Category");
        categorymi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorymiActionPerformed(evt);
            }
        });
        jMenu2.add(categorymi);

        subcatmi.setText("SubCategory");
        subcatmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcatmiActionPerformed(evt);
            }
        });
        jMenu2.add(subcatmi);

        mDiscount.setText("Discount");
        mDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDiscountActionPerformed(evt);
            }
        });
        jMenu2.add(mDiscount);

        jMenuItem4.setText("Package");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu11.setText("Bookings");

        coupons.setText("Coupons");
        coupons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponsActionPerformed(evt);
            }
        });
        jMenu11.add(coupons);

        jMenuBar1.add(jMenu11);
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menucpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucpActionPerformed
        ChangePasswordmi st = new ChangePasswordmi(con);
Dimension desktopSize = dp.getSize();
Dimension jInternalFrameSize = st.getSize();
st.setLocation((desktopSize.width - jInternalFrameSize.width)
        /2,
(desktopSize.height- jInternalFrameSize.height)/2);
st.setSize(380,346);
 st.setVisible(true); 
dp.add(st);
    }//GEN-LAST:event_menucpActionPerformed

    private void logoutmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmiActionPerformed


dispose();


    }//GEN-LAST:event_logoutmiActionPerformed

    private void exitmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmiActionPerformed
    try{ 
       
        con.close();
    System.exit(0);
    } 
    catch (SQLException ex) {
       ex.printStackTrace();
       JOptionPane.showMessageDialog(this, "some error occured");
    }
    }//GEN-LAST:event_exitmiActionPerformed

    private void departmentmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentmiActionPerformed
        departments x = new departments(con);
        x.setSize(700,500);
        Dimension desktopSize = dp.getSize();
Dimension jInternalFrameSize = x.getSize();
x.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        
        
        x.setVisible(true);
        dp.add(x);
    }//GEN-LAST:event_departmentmiActionPerformed

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
         
        Employees emp = new Employees(con);
        emp.setSize(900,600);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = emp.getSize();
emp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        emp.setVisible(true);
        dp.add(emp);
        
    }//GEN-LAST:event_EmployeeActionPerformed

    private void designationmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationmiActionPerformed
         Designation dd = new Designation(con);
        dd.setSize(600,480);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = dd.getSize();
dd.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        dd.setVisible(true);
        dp.add(dd);
    }//GEN-LAST:event_designationmiActionPerformed

    private void categorymiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorymiActionPerformed
          category c = new category(con);
        c.setSize(730,410);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = c.getSize();
c.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        c.setVisible(true);
        dp.add(c);
    }//GEN-LAST:event_categorymiActionPerformed

    private void subcatmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcatmiActionPerformed
        SubCategory s = new SubCategory(con);
        s.setSize(780,520);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = s.getSize();
s.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        s.setVisible(true);
        dp.add(s);
    }//GEN-LAST:event_subcatmiActionPerformed

    private void mDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDiscountActionPerformed
          Discount d = new Discount(con);
        d.setSize(770,520);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = d.getSize();
d.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        d.setVisible(true);
        dp.add(d);

    }//GEN-LAST:event_mDiscountActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
          Package1 p = new Package1(con);
        p.setSize(790,570);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = p.getSize();
p.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        p.setVisible(true);
        dp.add(p);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void couponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponsActionPerformed
  Coupons cc = new Coupons(con);
        cc.setSize(730,700);
        Dimension desktopSize = dp.getSize();
        Dimension jInternalFrameSize = cc.getSize();
cc.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height - jInternalFrameSize.height)/2);
        
        
        cc.setVisible(true);
        dp.add(cc);

    }//GEN-LAST:event_couponsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuItems(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Employee;
    private javax.swing.JMenuItem categorymi;
    private javax.swing.JMenuItem coupons;
    private javax.swing.JMenuItem departmentmi;
    private javax.swing.JMenuItem designationmi;
    private DesktopPaneBG dp;
    private javax.swing.JMenuItem exitmi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem logoutmi;
    private javax.swing.JMenuItem mDiscount;
    private javax.swing.JMenuItem menucp;
    private javax.swing.JMenuItem subcatmi;
    // End of variables declaration//GEN-END:variables
}
