
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class Package1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Package1
     */
    Connection con;
    ArrayList categorylist = new ArrayList();
    ArrayList discountlist = new ArrayList();
    int flag;
    Vector data;
    int chk;

    public Package1(Connection con) {
        initComponents();
        this.con = con;
        chk = 0;
        fillCategory();
        filltable();
      

        flag = 0;

        data = new Vector();
    }

    void filltable() {

        try {
            Vector heading = new Vector();
            heading.add("Package ID");
            heading.add("Package Name");
            heading.add("Total Cost");

            String query = "select * from package1";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            Vector data = new Vector();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("pack_id"));
                row.add(rs.getString("package_name"));
                row.add(rs.getString("total_price"));

                data.add(row);
            }
            DefaultTableModel df = new DefaultTableModel(data, heading);
            packagetable.setModel(df);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error occured " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        packagetable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtpackid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbcat = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Ltotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setClosable(true);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 310, 763, 89);

        btnNew.setBackground(new java.awt.Color(242, 237, 240));
        btnNew.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(180, 410, 70, 29);

        jLabel5.setBackground(new java.awt.Color(252, 238, 24));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(130, 122, 122));
        jLabel5.setText("              Manage Packages");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 20, 280, 50);

        btnsave.setBackground(new java.awt.Color(242, 237, 240));
        btnsave.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave);
        btnsave.setBounds(350, 410, 59, 29);

        jButton1.setBackground(new java.awt.Color(242, 237, 240));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 410, 69, 29);

        packagetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        packagetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packagetableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(packagetable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 450, 783, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Package Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(27, 29, 110, 16);
        jPanel1.add(txtname);
        txtname.setBounds(184, 24, 156, 25);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Package ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(27, 72, 100, 16);

        txtpackid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpackidActionPerformed(evt);
            }
        });
        jPanel1.add(txtpackid);
        txtpackid.setBounds(184, 67, 156, 25);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Category");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(27, 115, 90, 16);

        cmbcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcatActionPerformed(evt);
            }
        });
        jPanel1.add(cmbcat);
        cmbcat.setBounds(184, 110, 156, 25);

        btnadd.setBackground(new java.awt.Color(242, 237, 240));
        btnadd.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(140, 190, 60, 29);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Total Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(27, 153, 130, 27);

        Ltotal.setBackground(new java.awt.Color(236, 236, 236));
        jPanel1.add(Ltotal);
        Ltotal.setBounds(184, 153, 156, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 60, 370, 230);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cikpurple-biru.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 790, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        int cindex = cmbcat.getSelectedIndex();
        String x[] = (String[]) categorylist.get(cindex);
        String catcode = x[0];
        fillTable(catcode, x[1]);
        TableModel tm = jTable1.getModel();
        int totalprice = 0;
        
        for (int i = 0; i < data.size(); i++) {

            int c = (int) tm.getValueAt(i, 2);

            totalprice += c;

        }
        Ltotal.setText(String.valueOf(totalprice));


    }//GEN-LAST:event_btnaddActionPerformed

    private void cmbcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcatActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        try {
            String packname1 = txtname.getText();
            String packid1 = txtpackid.getText();
            String price1 = Ltotal.getText();
            String sql = "insert into package1 (pack_id,package_name,total_price) values(?,?,?)";
            PreparedStatement p = con.prepareStatement(sql);
            p.setString(1, packid1);
            p.setString(2, packname1);
            p.setString(3, price1);

            p.executeUpdate();

            
            
           String sql1 = "select pack_id from package1 order by pack_id desc";
            PreparedStatement p1 = con.prepareStatement(sql1); 
             ResultSet rs=p1.executeQuery();
             String packid="0";
             
             if(rs.next())
             
                    packid=rs.getString("pack_id");
            
            
            TableModel tm = jTable1.getModel();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
               
                String catid = (String) tm.getValueAt(i, 0);
              String  sql2= "insert into packagedetails (packag_id, catg_id) values(?,?)";
                    PreparedStatement p2 = con.prepareStatement(sql2); 
                    p2.setString(1,packid);
                    p2.setString(2,catid);
                    
                     p2.executeUpdate();
                    

            }
            
            filltable();
                    

        } catch (SQLException ex) {
            Logger.getLogger(departments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String packid2 = txtpackid.getText();

            String sql = "delete from  package1 where pack_id=?";

            PreparedStatement p = con.prepareStatement(sql);
            p.setString(1, packid2);
            p.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data Deleted");
            filltable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error occured " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void packagetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packagetableMouseClicked
        int rowindex = packagetable.getSelectedRow();
        TableModel tm = packagetable.getModel();

        String packid = (String) tm.getValueAt(rowindex, 0);

        String packname = (String) tm.getValueAt(rowindex, 1);

        String price = (String) tm.getValueAt(rowindex, 2);

        txtpackid.setText(packid);
        txtname.setText(packname);
        Ltotal.setText(price);
    }//GEN-LAST:event_packagetableMouseClicked

    private void txtpackidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpackidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpackidActionPerformed
    void fillCategory() {
        try {
            String query = "select * from category";
            PreparedStatement ps = con.prepareStatement(query);

            ResultSet rs = ps.executeQuery();

            String category_array[] = new String[2];

            while (rs.next()) {
                category_array = new String[2];
                category_array[0] = rs.getString("category_id");
                category_array[1] = rs.getString("category_name");
                cmbcat.addItem(rs.getString("category_name"));
                categorylist.add(category_array);
            }
            flag = 1;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillTable(String catcode, String catname) {
        try {
            Vector heading = new Vector();
            heading.add("category_id");
            heading.add("category");
            heading.add("price");

            String query = "select * from subcategory where category_id =? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, catcode);
            ResultSet rs = ps.executeQuery();

            int price = 0;
            while (rs.next()) {
                price += Integer.parseInt(rs.getString("price"));

            }

            Vector row = new Vector();
            row.add(catcode);
            row.add(catname);
            row.add(price);
            data.add(row);
            DefaultTableModel df = new DefaultTableModel(data, heading);
            jTable1.setModel(df);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error occured " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ltotal;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbcat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable packagetable;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpackid;
    // End of variables declaration//GEN-END:variables
}
