
import static java.lang.Boolean.TRUE;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class SubCategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form SubCategory
     */Connection con;
      ArrayList categorylist = new ArrayList();
      int flag;
    public SubCategory(Connection con) {
        initComponents();
        this.con = con;
        flag = 0;
        fillCategory();
        fillTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsubid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsubname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkactive = new javax.swing.JCheckBox();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnmodify = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        cmbcat = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(222, 217, 217));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel1.setText("Subcategory ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(24, 38, 120, 28);

        txtsubid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubidActionPerformed(evt);
            }
        });
        jPanel1.add(txtsubid);
        txtsubid.setBounds(170, 40, 132, 25);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel2.setText("Subcategory Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 95, 140, 28);
        jPanel1.add(txtsubname);
        txtsubname.setBounds(170, 90, 132, 25);

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel3.setText("Category Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(24, 146, 120, 20);

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel4.setText("Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 61, 20);

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtprice);
        txtprice.setBounds(170, 190, 132, 25);

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel5.setText("Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(24, 242, 60, 20);

        checkactive.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        checkactive.setText("Active");
        checkactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkactiveActionPerformed(evt);
            }
        });
        jPanel1.add(checkactive);
        checkactive.setBounds(170, 240, 80, 29);

        btnNew.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);
        btnNew.setBounds(23, 290, 60, 29);

        btnSave.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(97, 290, 60, 29);

        btnmodify.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnmodify.setText("Modify");
        btnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodify);
        btnmodify.setBounds(170, 290, 69, 29);

        btndel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        jPanel1.add(btndel);
        btndel.setBounds(260, 290, 70, 30);

        cmbcat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcatItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbcat);
        cmbcat.setBounds(170, 140, 132, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 130, 350, 343);

        jPanel2.setBackground(new java.awt.Color(222, 217, 217));
        jPanel2.setLayout(null);

        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        catTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 370, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(390, 150, 370, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zzz.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 780, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
      void fillCategory()
    {
        try{
        String query="select * from category" ;
PreparedStatement ps= con.prepareStatement(query);
 

 ResultSet rs=ps.executeQuery();

 
  String category_array[]=new String[2];
     category_array[0]="select";
     category_array[1]="0";
     cmbcat.addItem("Select");
     categorylist.add(category_array);
 while(rs.next()){
      category_array=new String[2];
     category_array[0]=rs.getString("category_id");
     category_array[1]=rs.getString("category_name");
     cmbcat.addItem(rs.getString("category_name"));
     categorylist.add(category_array);
 }
 flag =1;
 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
     
      void fillTable()
    {
        try
        {
        Vector heading=new Vector();
        heading.add("Sub ID");
        heading.add("Sub Name");
        heading.add("Category");
        heading.add("Price");
        heading.add("Status");
        
        
        
        String query="select * from subcategory,category where category.category_id=subcategory.category_id";
        PreparedStatement ps=con.prepareStatement(query);
        ResultSet rs=ps.executeQuery();
        Vector data=new Vector();
        while(rs.next())
        {
            Vector row=new Vector();
            row.add(rs.getString("sub_id"));
            row.add(rs.getString("sub_name"));
            row.add(rs.getString("category_id"));
            row.add(rs.getString("price"));
            row.add(rs.getString("status"));
           
               
            data.add(row);
         }
            DefaultTableModel df=new DefaultTableModel(data,heading);
            catTable.setModel(df);
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured "+ex.getMessage());
            ex.printStackTrace();
        }
        
    
    }
    
    private void btnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifyActionPerformed
         try
        {
           
       
        String subid=txtsubid.getText();
        String subname = txtsubname.getText();

        String price = txtprice.getText();
     
       
        int category = cmbcat.getSelectedIndex();
            String x[]=(String[]) categorylist.get(category);
             String cat=x[1];
              
             String check;
             
             if(checkactive.isSelected()== true)
             {
                 check = "Active";
             }
             else
             {
                 check = "Inactive";
             }
             
      String sql = "update subcategory set sub_name= ? , category_id= ?, price= ?, status= ? where sub_id =?";

        PreparedStatement p = con.prepareStatement(sql);

        p.setString(1, subid);
        p.setString(2, subname);
        p.setString(3, cat);
        p.setString(4, price);
        p.setString(5, check);
       
        p.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data Updated");  
        fillTable();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured "+ex.getMessage());
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_btnmodifyActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        try
        {
            String subid=txtsubid.getText();
       
        String sql = "delete from  subcategory where sub_id=?";

        PreparedStatement p = con.prepareStatement(sql);
 p.setString(1, subid);
        p.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data Deleted");  
        fillTable();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured "+ex.getMessage());
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_btndelActionPerformed

    private void txtsubidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubidActionPerformed

    private void cmbcatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcatItemStateChanged
          if(flag==1)
        {
        int index=cmbcat.getSelectedIndex();
         String x[]=(String []) categorylist.get(index);
        }
    }//GEN-LAST:event_cmbcatItemStateChanged

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtsubid.setText("");
        txtsubname.setText("");
        txtprice.setText("");
        checkactive.setSelected(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try {
             String subid = txtsubid.getText();
             if(subid.length() == 0)
             {
                 JOptionPane.showMessageDialog(this,"Fill SubCategory id");
                 
             }
             String subname = txtsubname.getText();
             if(subname.length() == 0)
             {
                 JOptionPane.showMessageDialog(this,"Fill SubCategory Name");
                 
             }
             int category = cmbcat.getSelectedIndex();
             String x[]=(String[]) categorylist.get(category);
             String cat =x[0];
        
             String price = txtprice.getText();
             String check;
             
             if(checkactive.isSelected()== true)
             {
                 check = "Active";
             }
             else
             {
                 check = "Inactive";
             }
             String sql = "insert into subcategory(SUB_ID, SUB_NAME, CATEGORY_ID,PRICE,STATUS) values(?,?,?,?,?)";
             PreparedStatement p = con.prepareStatement(sql);
             
             p.setString(1, subid);
             p.setString(2, subname);
             p.setString(3, cat);
             p.setString(4, price);
             p.setString(5, check);
             
             p.executeUpdate();
             
             JOptionPane.showMessageDialog(this, "Data Saved");
             fillTable();
         } catch (SQLException ex) {
             Logger.getLogger(SubCategory.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void catTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTableMouseClicked
          int rowindex = catTable.getSelectedRow();
        TableModel tm = catTable.getModel();

        String subcatid = (String) tm.getValueAt(rowindex, 0);
        String subcatname = (String) tm.getValueAt(rowindex, 1);
        String category  = (String) tm.getValueAt(rowindex, 2);
        String price = (String) tm.getValueAt(rowindex, 3);
        String status = (String) tm.getValueAt(rowindex, 4);
        
          txtsubid.setText(subcatid);
          txtsubname.setText(subcatname);
          txtprice.setText(price);
          
          
          if(status.equals("Active"))
          {
              
              checkactive.setSelected(true);
          }
         else
          {
              checkactive.setSelected(false);
          }
          
          
         for(int i=0;i<categorylist.size();i++)
         {
           String x[]=(String []) categorylist.get(i);
             if(x[1].equals(category))
             {
                  cmbcat.setSelectedIndex(i);
                break;
             }
         }
                               

         
         
         
         
    }//GEN-LAST:event_catTableMouseClicked

    private void checkactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkactiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnmodify;
    private javax.swing.JTable catTable;
    private javax.swing.JCheckBox checkactive;
    private javax.swing.JComboBox<String> cmbcat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsubid;
    private javax.swing.JTextField txtsubname;
    // End of variables declaration//GEN-END:variables
}
